# Generated by Django 5.1.1 on 2024-09-18 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=28, null=True)),
                ('edad', models.CharField(max_length=3)),
                ('cedula', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=11)),
                ('email_paciente', models.CharField(max_length=24)),
                ('observaciones', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=28)),
                ('email', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='radiografias/')),
                ('id_historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.historiapaciente')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=8)),
                ('probabilidad', models.CharField(max_length=4, null=True)),
                ('recomendaciones', models.TextField(max_length=500)),
                ('id_imagen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.imagenes')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
