# Generated by Django 4.2.16 on 2024-10-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=8)),
                ('probabilidad', models.CharField(max_length=4)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_antecedente', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('cedula', models.CharField(max_length=12)),
                ('sexo', models.CharField(max_length=6)),
                ('peso', models.CharField(max_length=3)),
                ('altura', models.IntegerField()),
                ('telefono', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255)),
                ('edad', models.CharField(max_length=3)),
                ('fecha_nacimiento', models.DateField()),
                ('registro', models.DateField(auto_now=True)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_medico', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.CharField(max_length=255)),
                ('fecha_consulta', models.DateField()),
                ('observaciones', models.TextField()),
                ('recomendaciones', models.TextField(max_length=1000)),
                ('medicacion', models.CharField(max_length=255)),
                ('fecha_informe', models.DateField(auto_now=True)),
                ('id_analisis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.analisis')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='radiografias/')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AntecedentesPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedente_descrip', models.TextField(blank=True, null=True)),
                ('id_antecedentesID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.antecedentesid')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente')),
            ],
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_imagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.imagen'),
        ),
    ]
