# Generated by Django 4.2.16 on 2024-11-04 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='id_analisis',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='id_medico',
        ),
        migrations.AddField(
            model_name='analisis',
            name='fecha_analisis',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='recomendaciones',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='RelacionMedicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_medico', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente')),
            ],
        ),
    ]
