# Generated by Django 4.2.16 on 2024-09-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacienteusuario',
            name='email',
            field=models.CharField(default='lmao', max_length=255),
            preserve_default=False,
        ),
    ]
