# Generated by Django 4.2.16 on 2024-10-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_informe_id_analisis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='id_analisis',
        ),
        migrations.AlterField(
            model_name='informe',
            name='recomendaciones',
            field=models.TextField(),
        ),
    ]
