# Generated by Django 5.1.1 on 2024-09-19 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_analisis_id_imagen_remove_analisis_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisis',
            name='id_Hpaciente',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='id_analisis',
        ),
        migrations.AddField(
            model_name='analisis',
            name='id_imagen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.imagenes'),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='id_Hpaciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.historiapaciente'),
        ),
    ]
