# Generated by Django 4.2.16 on 2024-09-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_pacienteusuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=255),
        ),
    ]
