# Generated by Django 4.2.16 on 2024-12-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_paciente_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='antecedente_descrip',
            field=models.TextField(blank=True, default='No aplica'),
        ),
    ]
