# Generated by Django 4.2.16 on 2024-10-14 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_informe_id_analisis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nombre',
        ),
    ]
