# Generated by Django 4.2.16 on 2024-10-03 19:26

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', usuario.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[(1, 'Medico'), (1, 'Paciente')], default='Medico', max_length=100),
        ),
    ]
