# Generated by Django 5.1.1 on 2024-09-19 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_remove_analisis_id_hpaciente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
