# Generated by Django 4.2.16 on 2024-09-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentesid',
            name='alergologicos',
        ),
        migrations.RemoveField(
            model_name='antecedentesid',
            name='cardiovasculares',
        ),
        migrations.RemoveField(
            model_name='antecedentesid',
            name='familiares',
        ),
        migrations.RemoveField(
            model_name='antecedentesid',
            name='medicos',
        ),
        migrations.RemoveField(
            model_name='antecedentesid',
            name='quirurgicos',
        ),
        migrations.RemoveField(
            model_name='antecedentesid',
            name='sociales',
        ),
        migrations.RemoveField(
            model_name='antecedentesid',
            name='vacunacion',
        ),
        migrations.AddField(
            model_name='antecedentesid',
            name='tipo_antecedente',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
