# Generated by Django 4.2.16 on 2024-10-04 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_user_managers_alter_user_rol'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', usuario.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_usuario_paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='id_paciente', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[(1, 'Medico'), (1, 'Paciente')], default='Medico', max_length=20),
        ),
    ]
