# Generated by Django 4.2.16 on 2024-10-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_username_user_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='username',
        ),
    ]
