# Generated by Django 4.2.16 on 2024-09-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_antecedentesid_alergologicos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentespaciente',
            name='id_antecedentesID',
        ),
        migrations.AddField(
            model_name='antecedentespaciente',
            name='id_antecedentesID',
            field=models.ManyToManyField(to='usuario.antecedentesid'),
        ),
    ]
