# Generated by Django 4.2.16 on 2024-10-04 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_user_managers_paciente_id_usuario_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedentespaciente',
            name='id_antecedentesID',
        ),
        migrations.AddField(
            model_name='antecedentespaciente',
            name='id_antecedentesID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='usuario.antecedentesid'),
            preserve_default=False,
        ),
    ]
