# Generated by Django 4.2.16 on 2024-10-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_rename_nombre_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
