# Generated by Django 4.2.16 on 2024-09-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_remove_antecedentespaciente_id_antecedentesid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='correo',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='analisis',
            name='probabilidad',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='analisis',
            name='resultado',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='antecedentesid',
            name='tipo_antecedente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medicousuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='medicousuario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicousuario',
            name='password',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='pacienteusuario',
            name='clave_acceso',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='pacienteusuario',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
