# Generated by Django 4.2.16 on 2024-12-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_antecedentespaciente_antecedente_descrip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informe',
            old_name='medicacion',
            new_name='antecedentes_importancia',
        ),
        migrations.RenameField(
            model_name='informe',
            old_name='observaciones',
            new_name='caracterizado',
        ),
        migrations.RenameField(
            model_name='informe',
            old_name='recomendaciones',
            new_name='examenes',
        ),
        migrations.RenameField(
            model_name='informe',
            old_name='fecha_consulta',
            new_name='inicio_enfermedad',
        ),
        migrations.RemoveField(
            model_name='informe',
            name='motivo_consulta',
        ),
        migrations.AddField(
            model_name='informe',
            name='frecuencia_cardiaca',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='frecuencia_respiratoria',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='recomendacion',
            field=models.TextField(default='aaaaaa', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='saturacion_oxigeno',
            field=models.IntegerField(default=95),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informe',
            name='tension_arterial',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='antecedente_descrip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
