# Generated by Django 4.2.16 on 2024-12-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_rename_medicacion_informe_antecedentes_importancia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='probabilidad',
            field=models.CharField(max_length=10),
        ),
    ]
