# Generated by Django 4.2.16 on 2024-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_remove_antecedentespaciente_id_antecedentesid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='recomendaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentespaciente',
            name='antecedente_descrip',
            field=models.TextField(blank=True, null=True),
        ),
    ]
