# Generated by Django 4.2.16 on 2024-10-16 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='id_medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
