# Generated by Django 4.2.16 on 2024-10-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_informe_fecha_consulta_informe_fecha_informe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
