# Generated by Django 4.2.16 on 2024-10-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_analisis_id_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='id_paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente'),
        ),
    ]
