# Generated by Django 4.2.16 on 2024-10-16 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_analisis_id_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='id_medico',
        ),
        migrations.CreateModel(
            name='RelacionMedicoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_medico', to=settings.AUTH_USER_MODEL)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.paciente')),
            ],
        ),
    ]
