# Generated by Django 4.2.16 on 2024-10-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_remove_paciente_id_medico_relacionmedicopaciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='fecha_analisis',
            field=models.DateField(auto_now=True),
        ),
    ]
